name: "ANSI to HTML"
description: "Escapes ANSI color escape sequences into HTML HEX colors."
author: "Justin McCormick <me@justinmccormick.com>"
branding:
  icon: "cloud-lightning"
  color: "blue"
inputs:
  input:
    description: "The raw input containing ANSI color codes. An input or path must be specified, but not both."
    required: false
  path:
    description: "The path to the file containing ANSI color codes. An input or path must be specified, but not both."
    required: false
  encoding:
    description: "The encoding for the raw input. Defaults to utf8."
    default: "utf8"
    required: true
outputs:
  contents:
    description: "The input or contents of path where all ANSI codes have been replaced with HTML color codes."
runs:
  using: "node16"
  main: "./index.js"
